//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation
    {
        public int Uid { get; set; }
        public Nullable<int> FirstNumber { get; set; }
        public Nullable<int> SecondNumber { get; set; }
        public string CommandText { get; set; }
        public Nullable<int> Result { get; set; }
        public string CommandOperator { get; set; }
    }
}
